### ISSUE TITLE
Pandas.jl dataframe unhashable

### ISSUE THREAD

**Issue by fuzzybear3965** [JuliaPy/Pandas.jl#12]
I've been trying to replicate a set of Python instructions in Julia. The below Python script works in Python3 (I made sure to set `ENV["PYTHON"]` appropriately) but not in Julia.

_test.py_
```python
import pandas as pandas

data = pandas.read_csv("test.csv");
m = fbp.Prophet()
m.fit(data)
```

_test1.jl_
```julia
import PyCall
PyCall.@pyimport pandas as pandas
PyCall.@pyimport fbprophet as fbp

data = pandas.read_csv("test.csv")
m = fbp.Prophet()
m[:fit](data)
```
I also tried _test2.jl_. The stack trace appears to be the same.
_test2.jl_
```julia
import PyCall
import Pandas
PyCall.@pyimport fbprophet as fbp

data = Pandas.DataFrame(Pandas.read_csv("test.csv"))
m = fbp.Prophet()
m[:fit](data)
```

### Stacktrace
```
ERROR: LoadError: PyError (:PyDict_SetItem) <class 'TypeError'>
TypeError("unhashable type: 'numpy.ndarray'",)

 in pyerr_check at C:\Users\JohnRinehart\.julia\v0.5\PyCall\src\exception.jl:56 [inlined]
 in pyerr_check at C:\Users\JohnRinehart\.julia\v0.5\PyCall\src\exception.jl:61 [inlined]
 in macro expansion at C:\Users\JohnRinehart\.julia\v0.5\PyCall\src\exception.jl:81 [inlined]
 in PyCall.PyObject(::Dict{Any,Any}) at C:\Users\JohnRinehart\.julia\v0.5\PyCall\src\conversions.jl:548
 in macro expansion at C:\Users\JohnRinehart\.julia\v0.5\PyCall\src\exception.jl:78 [inlined]
 in PyCall.PyObject(::Dict{Any,Any}) at C:\Users\JohnRinehart\.julia\v0.5\PyCall\src\conversions.jl:548
 in map(::Type{T}, ::Tuple{Dict{Any,Any}}) at .\tuple.jl:92
 in #_pycall#66(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::Dict{Any,Any}, ::Vararg{Dict{Any,Any},N}) at C:\Users\JohnRinehart\.julia\v0.5\PyCall\src\PyCall.jl:539
 in _pycall(::PyCall.PyObject, ::Dict{Any,Any}, ::Vararg{Dict{Any,Any},N}) at C:\Users\JohnRinehart\.julia\v0.5\PyCall\src\PyCall.jl:539
 in #pycall#70(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::Type{PyCall.PyAny}, ::Dict{Any,Any}, ::Vararg{Dict{Any,Any},N}) at C:\Users\JohnRinehart\.julia\v0.5\PyCall\src\PyCall.jl:573
 in pycall(::PyCall.PyObject, ::Type{PyCall.PyAny}, ::Dict{Any,Any}, ::Vararg{Dict{Any,Any},N}) at C:\Users\JohnRinehart\.julia\v0.5\PyCall\src\PyCall.jl:573
 in #call#71(::Array{Any,1}, ::PyCall.PyObject, ::Dict{Any,Any}, ::Vararg{Dict{Any,Any},N}) at C:\Users\JohnRinehart\.julia\v0.5\PyCall\src\PyCall.jl:576
 in (::PyCall.PyObject)(::Dict{Any,Any}, ::Vararg{Dict{Any,Any},N}) at C:\Users\JohnRinehart\.julia\v0.5\PyCall\src\PyCall.jl:576
 in include_from_node1(::String) at .\loading.jl:488
 in process_options(::Base.JLOptions) at .\client.jl:262
 in _start() at .\client.jl:318
while loading C:\Users\JohnRinehart\Downloads\test\test.jl, in expression starting on line 9
```

**Comment by fuzzybear3965** [comment]
I'm moving the conversation from [here](https://github.com/JuliaPy/PyCall.jl/issues/376#issuecomment-290768001) to here.

If I can run the above Python file just fine, then why would introducing PyCall/Pandas.jl into the mix not be the source of the issue?

**Comment by malmaud** [comment]
PyCall might be; just not Pandas.jl, since Pandas.jl isn't involved at all in `test1.jl`. 

I'm having trouble reproducing since this works fine me:

```julia
using PyCall
using Pandas


@pyimport datetime
x=[datetime.date(2017,1,1), datetime.date(2017,1,2)]
y=[1.0,2.0]
df=DataFrame(Dict("ds"=>x,"y"=>y))

@pyimport fbprophet

m=fbprophet.Prophet()
m[:fit](df)

```

**Comment by fuzzybear3965** [comment]
@malmaud, my friend who's having issues is having trouble whenever he imports a CSV into a dataframe. He doesn't have his issues when he generates random data in a dataframe. Would you mind importing a CSV (columns, "ds" and "y") and tell me if that works for you, too?

**Comment by malmaud** [comment]
Can you link me to a problematic  CSV?

**Comment by fuzzybear3965** [comment]
No problem. Check out [this one](https://hastebin.com/kayunolako.css).

**Comment by malmaud** [comment]
Still works:

```julia
using PyCall
using Pandas


df=read_csv("test.csv")
@pyimport fbprophet

m=fbprophet.Prophet()
m[:fit](df)


```

**Comment by fuzzybear3965** [comment]
That's strange, I just ran your code. I got the same error as before. Can you please provide your Python, PyCall.jl, Pandas.jl, Julia, and fbprophet versions?

Thanks!

**Comment by malmaud** [comment]
maltop:Documents malmaud$ python --version
Python 2.7.13 :: Anaconda 4.3.0 (x86_64)

maltop:Documents malmaud$ julia6 --version
julia version 0.6.0-pre.alpha

 - PyCall                        1.11.1             master
- Pandas                        0.4.0              master

uccessfully installed fbprophet-0.1.post1

**Comment by fuzzybear3965** [comment]
> Python 2.7.13 :: Anaconda 4.3.0 (x86_64)
 
I think that's it. I'm using Python3 for my work because I [installed PyStan manually](http://pystan.readthedocs.io/en/latest/windows.html). Our versions of PyCall, Pandas, and fbprophet are the same. Our julia versions differ, but I'll install the pre-alpha and let you know if that fixes it.

I'll try with Anaconda and Python2.7 later.

**Comment by malmaud** [comment]
Ah, Python 3. I think the group of people using PyCall are generally on
Python 2 so it wouldn't surprise me if there are some rough edges in using
Python 3  with PyCall.

**Comment by fuzzybear3965** [comment]
I'll go back [over there](https://github.com/JuliaPy/PyCall.jl/issues/376#issuecomment-290768001) and see if we can whip up a solution. Thanks, @malmaud.
