### ISSUE TITLE
Plotting a Pandas.jl dataframe with Python seaborn

### ISSUE THREAD

**Issue by juliohm** [JuliaPy/Pandas.jl#14]
For some reason I cannot reproduce the example in the seaborn webpage:

```julia
using Pandas, PyCall
@pyimport seaborn as sns

tips = sns.load_dataset("tips") # or any Pandas.jl dataframe
sns.violinplot(x="day", y="total_bill", data=tips)
```

The example works if I run it in the Python interpreter directly. In Julia, it returns this error:

>PyError (:PyObject_Call) <class 'TypeError'>
TypeError("float() argument must be a string or a number, not 'dict'",)
  File "/home/juliohm/.local/lib/python3.6/site-packages/seaborn/categorical.py", line 2175, in boxplot
    width, fliersize, linewidth)
  File "/home/juliohm/.local/lib/python3.6/site-packages/seaborn/categorical.py", line 426, in __init__
    self.establish_variables(x, y, hue, data, orient, order, hue_order)
  File "/home/juliohm/.local/lib/python3.6/site-packages/seaborn/categorical.py", line 154, in establish_variables
    orient = self.infer_orient(x, y, orient)
  File "/home/juliohm/.local/lib/python3.6/site-packages/seaborn/categorical.py", line 347, in infer_orient
    elif is_not_numeric(y):
  File "/home/juliohm/.local/lib/python3.6/site-packages/seaborn/categorical.py", line 327, in is_not_numeric
    np.asarray(s, dtype=np.float)
  File "/usr/lib/python3.6/site-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)

 >in pyerr_check at /home/juliohm/.julia/v0.5/PyCall/src/exception.jl:56 [inlined]
 in pyerr_check at /home/juliohm/.julia/v0.5/PyCall/src/exception.jl:61 [inlined]
 in macro expansion at /home/juliohm/.julia/v0.5/PyCall/src/exception.jl:81 [inlined]
 in #_pycall#66(::Array{Any,1}, ::Function, ::PyCall.PyObject) at /home/juliohm/.julia/v0.5/PyCall/src/PyCall.jl:556
 in (::PyCall.#kw##_pycall)(::Array{Any,1}, ::PyCall.#_pycall, ::PyCall.PyObject) at ./<missing>:0
 in #pycall#70(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::Type{PyCall.PyAny}) at /home/juliohm/.julia/v0.5/PyCall/src/PyCall.jl:573
 in (::PyCall.#kw##pycall)(::Array{Any,1}, ::PyCall.#pycall, ::PyCall.PyObject, ::Type{PyCall.PyAny}) at ./<missing>:0
 in #call#71(::Array{Any,1}, ::PyCall.PyObject) at /home/juliohm/.julia/v0.5/PyCall/src/PyCall.jl:576
 in (::PyCall.#kw#PyObject)(::Array{Any,1}, ::PyCall.PyObject) at ./<missing>:0

**Comment by fuzzybear3965** [comment]
May I suggest importing your data without using Pandas.jl to generate a dataframe. I've had problems with Pandas.jl and DataFrames, myself. I've been led to [this solution](https://github.com/JuliaPy/PyCall.jl/issues/376#issuecomment-293411255).

**Comment by juliohm** [comment]
Thanks for the comment @fuzzybear3965, can you please elaborate on importing the data without Pandas.jl?

**Comment by malmaud** [comment]
I'll fix this soon; it worked at some point but changes to PyCall.jl have broken it.

**Comment by malmaud** [comment]
Also not sure if you're aware of https://github.com/JuliaPy/Seaborn.jl.

**Comment by fuzzybear3965** [comment]
@juliohm, I can't. I'm too stupid right now :/. If I get smarter then I'll get back at you.

**Comment by juliohm** [comment]
@malmaud how could I use Seaborn.jl directly in this case? Can you share a code snippet?

**Comment by malmaud** [comment]
This issue doesn't have anything to do with Pandas.jl - your code snippet doesn't even use Pandas.jl. This is just because PyCall is automatically converting the dataframe returned by `load_dataset` to a dictionary.

**Comment by malmaud** [comment]
We're going to change PyCall.jl to not automatically convert Pandas dataframes to dictionaries, which will make your snippet work. But for the record, the Seaborn.jl code would be:

```julia
using Seaborn
tips = load_dataset("tips")
violinplot(x="day", y="total_bill", data=tips)
```

**Comment by juliohm** [comment]
@malmaud as a side note, the function `load_dataset` is not accessible through `Seaborn.jl`, can you please confirm?

**Comment by malmaud** [comment]
It is available -
https://github.com/JuliaPy/Seaborn.jl/blob/master/src/Seaborn.jl#L512

**Comment by juliohm** [comment]
Is it available in the latest tag of Seaborn.jl? I can't call it here, it doesn't autocomplete on the Julia prompt either.

**Comment by malmaud** [comment]
Oh, maybe not. I'll tag a new version.

**Comment by juliohm** [comment]
Thanks, I will migrate my scripts to Seaborn.jl.

**Comment by malmaud** [comment]
OK, Seaborn has been tagged.
