### ISSUE TITLE
`isempty` & `empty!`

### ISSUE THREAD

**Issue by rofinn** [JuliaPy/Pandas.jl#18]
It would be nice if `isempty` was consistent with `df.empty`.

Example)

```julia
julia> isempty(DataFrame(df))
false

julia> length(DataFrame(df))
0

julia> df[:empty]
true
```
Also, it would be nice if the `empty!` method was supported.

**Comment by malmaud** [comment]
Want to submit a PR? Should be an easy one.

**Comment by rofinn** [comment]
Sure. I think I already have the coding sitting around somewhere.
