### ISSUE TITLE
Julia has stopped: 3221226356

### ISSUE THREAD

**Issue by wuotre** [JuliaPy/Pandas.jl#23]
I'm importing a large text file (.dat 2GB), but both with the Pandas package and with Pycall, julia stops working without giving any error. I only get: "Julia has stopped: 3221226356".  The normal readdlm works but it too slow. Any idea what causes this sudden stop? I have tried both  read_csv and read_table.

**Comment by malmaud** [comment]
Does it work in you use Pandas directly in Python? Can you share the file, or it's too sensitive to share, some other file that crashes?

**Comment by wuotre** [comment]
I did not tried it directly in Python, but I have tried different sizes... There was no problem with 75000 rows and 3140 columns, while it stops at 100000 rows.  Doing these tests, I noticed that I misspecified the delimiter for importing and with the correct delimiter it works now. So maybe the issue is with parsing  large text lines? I cannot share the file as it is sensitive data.

**Comment by malmaud** [comment]
I can't know if it's a Julia-specific problem unless we find out if it also breaks when Julia isn't involved at all.

**Comment by wuotre** [comment]
I've checked it and python crashes, so it's not a julia specific problem.

**Comment by malmaud** [comment]
Alright, I'm going to close this then.
