### ISSUE TITLE
Describe not defined Bug

### ISSUE THREAD

**Issue by kleinash** [JuliaPy/Pandas.jl#24]
Issue: Unable to get overview of imported dataframe 

Situation: Using jupyter lab.  Dataframe generated in Python, saved to csv, imported into Julia with 
```julia
using Pandas
df = read_csv("/home/path/out.csv"); 
df[:column_name]
```
All that works just fine but when I run `describe(df)` I get
"UndefVarError: describe not defined" 

EDIT: I am on an old Julia 0.5.2 so this may have been updated since

**Comment by arshpreetsingh** [comment]
I am having the same issue, for DataFrames version - 0.10.1 and Julia version 0.6.0

**Comment by kleinash** [comment]
Ok I will reopen - I just didn't end up trying to look at the df.

**Comment by malmaud** [comment]
Should be an easy fix

**Comment by arshpreetsingh** [comment]
I am using Linux Binaries (I have not compiled 0.6.0 from source)Seems like Problem could be only with  provided binaries.

**Comment by malmaud** [comment]
@kleinash I can't reproduce on Julia 0.6. `describe` works fine for me.
@arshpreetsingh This package is totally unrelated to `DataFrames`.

**Comment by malmaud** [comment]
Oh, the problem might be if you import both `DataFrames` and `Pandas`. Both export a binding called `describe`, so you'd have to explicitly call `Pandas.describe` if you have both (or do `import Pandas: describe`)
