### ISSUE TITLE
"Not equal" sign wrongly passed to pandas query

### ISSUE THREAD

**Issue by GWeindel** [JuliaPy/Pandas.jl#26]
Using query with a not equal sign "!=" throws an error : 

Reproductible example : 
`df = DataFrame([[1,4,3],[2,3,5],[4,5,6],[3,2,5]], columns=["a", "b", "c"])`
`query(df, :(a != 1))`
error : 
`ERROR: PyError (ccall(@pysym(:PyEval_EvalCode), PyPtr, (PyPtr, PyPtr, PyPtr), o, globals, locals)) <type 'exceptions.SyntaxError'>
SyntaxError('invalid syntax', ('<unknown>', 1, 3, 'a ~=1 \n'))
`
Query works when using ==. I guess the "!" is lost in translation

I'm on Julia 0.6.1 and pandas 0.6.2

**Comment by malmaud** [comment]
Hmm, I'll look into it.
