### ISSUE TITLE
HDFStore is not wrapped

### ISSUE THREAD

**Issue by mikehenninger** [JuliaPy/Pandas.jl#27]
Maybe this is considered an obscure function, but it isn't for my uses. Workaround below, but A) seems easy to wrap? B) I worry about two pandas imports floating around C) the copy overhead might get bad on bigger files?

workaround:
```
using PyCall
using Pandas
@pyimport pandas as pd
in_store = pd.HDFStore(hd5_with_dfs_in_it.hd5)
py_df = in_store[idx] #typeof(py_df) == PyCall.PyObject
df = Pandas.DataFrame(py_df) #typeof(df) == Pandas.Dataframe
```

**Comment by malmaud** [comment]
Do you want to submit a PR to implement this? Should be very simple.

**Comment by mikehenninger** [comment]
Honestly, no... I started using Julia literally yesterday, and I don't
think I'll be moving to developing on it after all. Thus I don't have the
skills or the aligned interests to do it well. I figured posting the issue
would be potentially helpful on my way out the door, basically :)

**Comment by ufechner7** [comment]
Being able to read pandas dataframes from an hdf5 store would be important for me, too.

**Comment by malmaud** [comment]
OK, I pushed an update to `master` that adds an `HDFStore` type with associated methods and a global `read_hdf` and `to_hdf` method. It worked in my testing, but I don't personally use HDF so do you want to try it out and make sure it does what you want? If it does, I'll tag a new release.

**Comment by malmaud** [comment]
I'll tag for now, but feel free to open a new issue if there are additional concerns.
