### ISSUE TITLE
Enable appveyor

### ISSUE THREAD

**Issue by davidanthoff** [JuliaPy/Pandas.jl#34]

**Comment by davidanthoff** [comment]
Bump :)

**Comment by malmaud** [comment]
Hmm, let's see if I remember how to do that.

**Comment by malmaud** [comment]
Why do you want it, given we already have Travis working? Is it mainly for testing against Windows? There isn't anything OS-specific in this simple package so I'm a little reluctant to deal with the mental overhead of another CI system, unless you think there's a tangible benefit.

**Comment by davidanthoff** [comment]
Yes, only reason is to test on Windows, and on 32 bit. Especially with packages that interact with other binaries like Python, that seems like a good idea? But clearly that is your call :)
