### ISSUE TITLE
selection fails

### ISSUE THREAD

**Issue by joytrust0609** [JuliaPy/Pandas.jl#39]
![default](https://user-images.githubusercontent.com/20922321/47139406-57176300-d2ee-11e8-8114-902d2f488377.png)

**iloc(df3)[2, 3]**  worked
iloc(df3)[1:2, 2:3] failed

**Comment by malmaud** [comment]
Can you post copy-pastable code instead of a screenshot so I can test it?

**Comment by milanhej** [comment]
Having the same issue.  Using your own sample code from the package introduction, the 
iloc(df3)[1:2,2:3] fails.  Apparently range selection with iloc is broken.


df2 = DataFrame(Dict(:income=>[45, 101, 87]), index=["Jake", "James", "Jill"])
df3 = merge(df, df2, left_on="name", right_index=true)
iloc(df3)[1:2, 2:3]

MethodError: no method matching -(::UnitRange{Int64}, ::Int64)
Closest candidates are:
  -(!Matched::Complex{Bool}, ::Real) at complex.jl:298
  -(!Matched::Missing, ::Number) at missing.jl:93
  -(!Matched::Base.CoreLogging.LogLevel, ::Integer) at logging.jl:107
