### ISSUE TITLE
LoadError: PyError -- Import Error('No module named pandas', )

### ISSUE THREAD

**Issue by Mohitsharma44** [JuliaPy/Pandas.jl#4]
Hi, I am trying to use Pandas in julia, but using this package gives me:

```
ERROR: LoadError: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('No module named pandas',)

 [inlined code] from /home/mohitsharma44/.julia/v0.4/PyCall/src/exception.jl:81
 in pyimport at /home/mohitsharma44/.julia/v0.4/PyCall/src/PyCall.jl:302
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in require at ./loading.jl:243
while loading /home/mohitsharma44/.julia/v0.4/Pandas/src/Pandas.jl, in expression starting on line 20
```

I have pandas installed (along with numpy via pip). 
Running `python -c "import pandas as pd; print pd.__version__"` outputs `0.17.1`

I installed Pandas package using Julia's

```
Pkg.clone("Pandas")
```

and then

```
using Pandas
```

I gave up and went with Conda way to install packages. It works with `conda.add("Pandas")` with some Warnings about deprecated methods but doesn't break.

Any ideas? Let me know if you need more information.

**Comment by malmaud** [comment]
Probably `PyCall` is not pointing to the same Python distribution that you have Pandas installed in. You should get a more informative error message now.
