### ISSUE TITLE
Subsetting

### ISSUE THREAD

**Issue by versipellis** [JuliaPy/Pandas.jl#45]
It's not immediately apparent to me how to subset in Pandas.jl compared to Python's pandas:

Where in Python pandas:
```
dftop30 = df[df['ORIGIN'].isin(top30)]
```

I roughly expect the Pandas.jl equivalent to be:
```
datatop30 = data[isin(data[:ORIGIN],top30),:]
```

This, however, results in:
```
PyError ($(Expr(:escape, :(ccall(#= /home/bversipellis/.julia/packages/PyCall/0jMpb/src/pyfncall.jl:44 =# @pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, pyargsptr, kw))))) <class 'TypeError'>
TypeError("'Series' objects are mutable, thus they cannot be hashed",)
```

**Comment by malmaud** [comment]
Can you post complete code that reproduces the problem? Then I can take a look.

**Comment by versipellis** [comment]
Sure.
```
using Pandas
df = DataFrame(Dict(:Group=>["Alpha", "Beta", "Alpha", "Charlie", "Beta", "Delta"], :name=>["James", "Jill", "Jake", "A name", "Yet another name", "Some person"]))
subset = ["Alpha","Delta"]

testsubset = df[isin(df[:Group],subset),:]
```
All I'm trying to do is subset a dataframe based on another object, which is trivial in Python pandas. The above code in Python for the last line:
```
testsubset = df[df['Group'].isin(subset)]
```

**Comment by malmaud** [comment]
You should index in Julia just like in Python:

`df[isin(...)]` without the extra `, :]` at the end. If you try doing that in Python, you get the same error message.

**Comment by versipellis** [comment]
Huh, weird, I had tried that before and run into an error. Looks like I'm doing it right now, sorry and thanks!

**Comment by malmaud** [comment]
No problem and thanks for checking out the package.
