### ISSUE TITLE
update for PyCall 1.90.0: o.foo, not o[:foo]

### ISSUE THREAD

**Issue by stevengj** [JuliaPy/Pandas.jl#50]
You will get zillions of deprecation warnings until you update: replace `o[:foo]` and `o["foo"]` with `o.foo` and `o."foo"`, respectively, for python objects `o`.

**Comment by malmaud** [comment]
Gotcha. I'll make that change and then push a new version that raises the lower bound on PyCall to the version that includes the dot syntax. (Or if anyone who sees this issue once to submit a PR that does the replacements, all the better).

**Comment by malmaud** [comment]
Closed in #51
