### ISSUE TITLE
Fresh install in v0.4.2 uses Range1 instead of UnitRange in Pandas.jl

### ISSUE THREAD

**Issue by yjk21** [JuliaPy/Pandas.jl#6]
To reproduce, in v0.4.2 Julia:
    Pkg.add("Pandas")
    using Pandas
    df = DataFrame()

This gives ERROR: LoadError: UndefVarError: Range1 not defined
Can be fixed by replacing Range1 in Pandas.jl:81 by UnitRange

**Comment by malmaud** [comment]
This has been fixed in master
