### ISSUE TITLE
Installation without super user

### ISSUE THREAD

**Issue by nantonel** [JuliaPy/Pandas.jl#62]
Hi! Thanks for the nice package!

I was wondering if it's really necessary to use the following command suggested in the README: 
```bash
sudo pip install pandas
```
which requires super user.
Wouldn't be better to completely rely on `Conda.jl`?
Additionally it looks like `pytables` also needs to be installed.

This is how I mange to install Pandas without super user:
```julia
julia> using Conda

julia> Conda.add("pandas"); Conda.add("pytables")

julia> Pkg.add("Pandas")
```
I believe all of this could be included in a [build script](https://julialang.github.io/Pkg.jl/v1/creating-packages/index.html#Adding-a-build-step-to-the-package-1).

**Comment by malmaud** [comment]
Good idea, I updated the README instructions to make it clearer that it isn't necessary to install anything as root.
