### ISSUE TITLE
Interaction with DataFrames.jl

### ISSUE THREAD

**Issue by diegozea** [JuliaPy/Pandas.jl#7]
Is It possible to convert a DataFrames' `DataFrame` into a Pandas' one? 
I want to use Pandas to plot DataFrames' data with [seaborn](https://stanford.edu/~mwaskom/software/seaborn/index.html) (using PyCall).

**Comment by ValdarT** [comment]
I also think it would be nice if there were functions to convert from and to a DataFrames' DataFrame. And perhaps from/to DataTables' DataTable as well.

**Comment by malmaud** [comment]
I'd gladly accept a pull request for that, but I probably won't implement it myself.

**Comment by ValdarT** [comment]
This can (now) easily be achived through [IterableTables](https://github.com/davidanthoff/IterableTables.jl).

```
using Pandas, DataFrames, IterableTables

df = Pandas.DataFrame(Dict(:age=>[27, 29, 27], :name=>["James", "Jill", "Jake"]))

DataFrames.DataFrame(df)
```

Not sure but perhaps it is worth adding it to the docs. In any case, I wanted to add this here in case someone stumbles on this problem and finds this issue.

**Comment by dharasim** [comment]
I use 

```julia
panda(df) = Pandas.DataFrame(Dict(n => df[n] for n in names(df)))
```

to convert a `DataFrames.DataFrame` to a `Pandas.DataFrame`. In a Seaborn call, I then just replace `df` by `panda(df)`.

The automatic conversion does, however, not work as far as I know.

**Comment by davidanthoff** [comment]
I think this issue can be closed. Conversion both ways should be working for quite a while already.

**Comment by malmaud** [comment]
Indeed. Thanks again @davidanthoff for getting this working smoothly.
