### ISSUE TITLE
Could you release new version e.g. 1.5.4 ?

### ISSUE THREAD

**Issue by terasakisatoshi** [JuliaPy/Pandas.jl#97]
Ref

Looks good. Just needs bumping version and releasing

_Originally posted by @bkamins in https://github.com/JuliaPy/Pandas.jl/pull/94#pullrequestreview-994824063_

**Comment by malmaud** [comment]
Yep, was just getting a few more PRs in first. Will bump now.

**Comment by malmaud** [comment]
Pending in https://github.com/JuliaRegistries/General/pull/64936

**Comment by terasakisatoshi** [comment]
Thank you so much!!!
